# Generated by Django 5.1.1 on 2024-09-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_agentrole_llmusecases_agent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusecases',
            name='task',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
